@startuml MetodoPago
(*) --> [Se genera el pago\n /generarPago()]Generado
if "Con Tarjeta?" then
    -->[Si (la tarjeta\n tiene saldo)\n /pagar()] Pagado
else
    --> [No, transferencia bancaria] Pago Pendiente
    --> Pagado
if "Pago aceptado?" then
    --> Completamente\n pagado
    --> (*)
else
    --> Rechazado
    if "Reintentar" then
        --> [Si]Generado
    else
        --> [No]Cancelado
        --> (*)
    
    
@enduml