@startuml Clinica Veterinaria
package Veterinaria{
    class Persona{
        - nombre : string
        - apellido : string
        - dni : Int
        - fechaNacimiento : Date
        - telefono : Int
        - email : string
    }

    class Cliente{
        - datosPersonales : Persona
        
        + verificarCliente()
        + crearCliente()
        + consultarEstado()
        + consultarCamara()
        + consultarHistorial()
    }

    class Veterinario{
        - datosPersonales : Persona
        - profesion : String

        + operar()
    }
 
    class Auxiliar{
        - datosPersonales : Persona
        - turno : string

        + cobrarCliente()
    }

    class Mascota{
        - nombre : string
        - raza : string
        - edad : string
        - sexo : string
        - dueno : Cliente

        + verificarMascota()
        + crearMascota()
        + modificarDueno()
    }

    class Consulta{
        - animal : Mascota
        - profesional : Veterinario
        - fecha : Datetime
        - tiempoTranscurrido : Int
        - importe : Double
        - resolucion : string
        - pago : Pago
        - recetas : List <Receta>
    }

    class Receta{
        - nombre : string
        - definicion : string
    }

    class Pago{
        - metodo : string

        + registrarPago()
        + aplicarRecargo()
    }

    class SistemaCamaras{
        - cantidad : int
        - listaMascotas : List<Mascota>

        + verVideo()
    }

    class Camara{
        - numero: int

        + verVideoCamara()
    }


    ' Herencia
    Cliente -up-|> Persona
    Veterinario -up-|> Persona
    Auxiliar -up-|> Persona

    ' Relaciones
    Cliente "1" --> "0-n" Mascota
    Consulta "0-n" -left-> "1" Mascota
    Consulta "0-n" -up-> "1" Veterinario
    Consulta -left-> "0-n" Receta
    Consulta -right-> Pago
    Cliente -> Pago
    SistemaCamaras -down-> Camara
    Cliente -> SistemaCamaras
}

package REIAC {
    class REIAC{
        + verificarMascota()
    }
}

package GestorContenidos <<Database>> { 
    class GestorContenidos{
        + guardarDiario()
        + generarInforme()
        + historialMascota()
    }
}

Mascota --> REIAC
GestorContenidos -up-> Consulta
' GestorContenidos -up-> Cliente
' GestorContenidos -up-> Mascota

@enduml